kubebeat agent integration Todos
build-security/beats pull request #13
Opened 2021-11-17 15:45 UTC by DaveSys911

## What does this PR do?

Adds the necessary framework to fill out all  required boiler plate to integrate kubebeat to agent.
a few notes:
- Mage scripts will require writing
- This file is auto-generated by mage under the x-pack/elastic-agent sub dir and will include [agent-supported](x-pack/elastic-agent/pkg/agent/program/supported.go)

## Why is it important?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2021-11-17 16:09 UTC, eyalkraft commented
We need to find out how to run locally a beat that wasn't signed by elastic

2021-11-17 16:11 UTC, DaveSys911 commented
> We need to find out how to run locally (using a fleet managed fleet) a beat that wasn't signed by elastic

You mean fleet managed agent, and yes but we will start with the standalone.

2021-11-21 12:18 UTC, amirbenun requested changes

2021-11-21 12:18 UTC, amirbenun commented on kubebeat/kubebeat.yml
> -  ]
Why did you remove it?

2021-11-21 12:18 UTC, amirbenun commented on kubebeat/scripts/mage/package.go
> +// Licensed to Elasticsearch B.V. under one or more contributor
Can we remove the file?

2021-11-21 12:18 UTC, amirbenun commented on x-pack/osquerybeat/beater/osquerybeat.go
> +// ToDo Copy regsiterAction Handler to kubebeat
We can remove it right?

2021-11-21 12:47 UTC, DaveSys911 commented on x-pack/osquerybeat/beater/osquerybeat.go
> +// ToDo Copy regsiterAction Handler to kubebeat
Leave it for now as reference for Eyal

2021-11-21 12:49 UTC, DaveSys911 commented on kubebeat/kubebeat.yml
> -  ]
Auto-generated file as discussed will be added to config.go then it will appear there.

2021-11-21 12:49 UTC, DaveSys911 commented on kubebeat/scripts/mage/package.go
> +// Licensed to Elasticsearch B.V. under one or more contributor
Leave it as a placeholder please - Once we are done i am going to move some package logic from the main magefile here.

2021-11-21 12:52 UTC, amirbenun approved these changes

2021-11-21 12:54 UTC, merged