Functional Kube API Fetcher
build-security/beats pull request #29
Opened 2021-11-29 11:55 UTC by yashtewari

2021-12-02 14:47 UTC, ofiriro3 commented
I think that some files are missing, when I tried to run your branch I had to download "k8s.io/kubernetes/pkg/apis/policy".

Is there any chance that you missed an update in the go.mod + go.sum ?

2021-12-02 14:48 UTC, ofiriro3 commented on kubebeat/beater/kube.go
> +	psp, err := client.CoreV1().Pods("kube-system").List(context.Background(), v1.ListOptions{})
Can we export the string "kube-system" to a const variable?

2021-12-02 14:52 UTC, ofiriro3 commented on kubebeat/beater/kube.go
> +	psp, err := client.CoreV1().Pods("kube-system").List(context.Background(), v1.ListOptions{})
I didn't see that we use the pod's list in the function. Do we need it ?

2021-12-05 09:11 UTC, eyalkraft requested changes

2021-12-05 09:11 UTC, eyalkraft commented on kubebeat/beater/kube.go
> +	watcher, err := kubernetes.NewWatcher(client, &policy.PodSecurityPolicy{}, watchOptions, nil)
I wonder now, what will be the scope of our fetchers? will this fetcher be used for all types of k8s resources?
what about requirements for different benchmarks? relates to some work currently done by @ofiriro3

2021-12-06 10:50 UTC, yashtewari commented on kubebeat/beater/kube.go
> +	fmt.Println("RAW PSP, ERR", psp, err)
Yeah, I mentioned on one of the calls that I'll remove these things after one round of review, because it helps in debugging if there is any more development to be done.

2021-12-15 07:48 UTC, yashtewari commented on kubebeat/beater/kube.go
> +	psp, err := client.CoreV1().Pods("kube-system").List(context.Background(), v1.ListOptions{})
Now handling all required resources that I know of

2021-12-15 07:49 UTC, yashtewari commented on kubebeat/beater/kube.go
> +	fmt.Println("RAW PSP, ERR", psp, err)
Removed

2021-12-16 18:14 UTC, amirbenun requested changes

2021-12-16 18:14 UTC, amirbenun commented on kubebeat/beater/kube.go
> +	watcherlock.Do(func() {
I am not sure you have to use lock here. I think what you really want to have here is an `Init` method inside the `Fetcher` interface that gets called once at the beginning.

2021-12-16 18:14 UTC, amirbenun commented on kubebeat/beater/kube.go
> +		Namespace:   kubeSystemNamespace,
I don't think that all the watchers should watch only on the `kube-system` namespace. I believe `Role` and `RoleBinding` for example should be watched all across the cluster.

2021-12-16 18:14 UTC, amirbenun commented on kubebeat/beater/kube.go
> +		// &kubernetes.NetworkPolicy{},
I wonder if that list can be generalized a little bit. In case we realize EKS AWS requires some more resources, for example, we could use the same kubefetcher with a different resource type list.

2021-12-19 09:46 UTC, eyalkraft commented on go.mod
> +	go.uber.org/goleak v1.0.0
isn't used?

2021-12-20 08:11 UTC, yashtewari commented on kubebeat/beater/kube.go
> +	watcherlock.Do(func() {
This is a remnant from the leader lease code that I had removed from this PR.

2021-12-20 08:14 UTC, yashtewari commented on kubebeat/beater/kube.go
> +		Namespace:   kubeSystemNamespace,
Ah, will fetch namespaces and run those against each one of them.

2021-12-20 08:19 UTC, yashtewari commented on go.mod
> +	go.uber.org/goleak v1.0.0
Doesn't compile without this, it's because of a go.mod change that should have been included in a merged PR, but wasn't

2021-12-20 15:29 UTC, amirbenun commented on kubebeat/beater/kube.go
> +func (f *KubeFetcher) initWatcher(w kubernetes.Watcher, err error) error {
why do get an `er error` as a parameter here? Seems like you never uses it and always pass `nil`

2021-12-20 15:29 UTC, amirbenun commented on kubebeat/beater/kube.go
> +type requiredResource struct {
Nice I think that's basically what needs to be changed between different KubeAPI fetchers.
Meaning on the next iterations, we would like to `vanillaClusterResources` (or another name of course) from outside.

2021-12-20 17:55 UTC, yashtewari commented on kubebeat/beater/kube.go
> +func (f *KubeFetcher) initWatcher(w kubernetes.Watcher, err error) error {
`initWatcher` takes the output from `kubernetes.NewWatcher`, and it works because the input and output have a matching signature.

I've removed modified the function now to make more sense.

2021-12-20 17:57 UTC, yashtewari commented on kubebeat/beater/kube.go
> +type requiredResource struct {
Yup got the idea from what you mentioned about Ofir's work.

2021-12-20 18:07 UTC, amirbenun approved these changes

2021-12-21 07:35 UTC, merged