Feature/eks-data-collector-old-aws-sdk
build-security/beats pull request #32
Opened 2021-12-15 14:58 UTC by Ofir-Lapid

2021-12-15 16:03 UTC, Ofir-Lapid commented on kubebeat/beater/Iam_provider.go
> +	svc := iam.New(cfg)
I am wondering what is the cost of creating this svc every time (it relates to all of the providers)

It makes it stateless and less complex, but still I am not sure what is the right approach here

2021-12-15 16:08 UTC, Ofir-Lapid commented on kubebeat/beater/aws_kube_fetcher.go
> +	// TODO - Currently we do not know how to extract the ECR repository out of the image
Remind me to explain it in personal

2021-12-16 11:08 UTC, eyalkraft requested changes

2021-12-16 11:08 UTC, eyalkraft commented on kubebeat/beater/ecr_provider.go
> +/// When repoNames is nil, it will describe all the existing repositories
Having this nil special case just because this is how the AWS API works isn't clean. What about giving up on this argument?

2021-12-16 11:08 UTC, eyalkraft commented on kubebeat/beater/aws_kube_fetcher.go
> +	repositories, err := f.ecr.DescribeRepositories(f.cfg, ctx, nil)
now I see, see later comments.

2021-12-16 11:08 UTC, eyalkraft commented on kubebeat/beater/aws_kube_fetcher.go
> +	services, err := f.kubeClient.CoreV1().Services("").List(ctx, metav1.ListOptions{})
does this work? what does "" as namespace mean? please document

2021-12-16 11:08 UTC, eyalkraft commented on kubebeat/beater/aws_kube_fetcher.go
> +	return nodesInfo, err
maybe `nodesInfo, nil` ?

2021-12-16 11:08 UTC, eyalkraft commented on kubebeat/beater/aws_kube_fetcher.go
> +	return nodesInfo, err
Or just return `nodeList.Items, nil`? Will this be ok?

2021-12-16 11:08 UTC, eyalkraft commented on kubebeat/beater/aws_kube_fetcher.go
> +func (f AwsKubeFetcher) GetNodeDescription() ([]interface{}, error) {
why interface{} ?

2021-12-16 11:08 UTC, eyalkraft commented on kubebeat/beater/Iam_provider.go
> +type IamProvider struct {
My comments here apply to all providers.

2021-12-16 11:11 UTC, eyalkraft commented
also what about unit tests? see https://aws.amazon.com/blogs/developer/mocking-out-then-aws-sdk-for-go-for-unit-testing/

2021-12-16 11:22 UTC, ofiriro3 commented on kubebeat/beater/Iam_provider.go
> +	svc := iam.New(cfg)
To be honest I wasn't sure about the design I chose but I can reason why I decided to do it that way.

I wanted the providers to be stateless. I didn't want them to "store" any client as part of the class.
So each call will be independent of another call. For example, in the case of a client crash in one call, it won't affect any other usage. 

The big disadvantage here is obviously creating the client every time. Maybe it was a better solution, I'll wait for Amir to give a second thought about it.

I have no problem changing it if needed - I am not sure myself it was the right solution

2021-12-16 11:27 UTC, ofiriro3 commented on kubebeat/beater/Iam_provider.go
> +	ctx, cancel := context.WithTimeout(context.TODO(), 30*time.Second)
Mistake - will be fixed

2021-12-16 11:29 UTC, ofiriro3 commented on kubebeat/beater/aws_kube_fetcher.go
> +		log.Fatal(err)
fixed

2021-12-16 11:44 UTC, ofiriro3 commented on kubebeat/beater/aws_kube_fetcher.go
> +	ctx2, cancel2 := context.WithTimeout(context.TODO(), 30*time.Second)
I am wondering about this one.

I tried to think if all these functions should be private instead of public and I'll explain.
If you want to get specific data for AWS you can always use the provider, but - is there any case when you will want to use from the outside a "CIS data collector" ? I don't think so..

So if that's the case and the functions should be private I see no reason to send the CTX as a parameter, each CIS rule can define its own ctx.

WDT ?

2021-12-16 11:46 UTC, ofiriro3 commented on kubebeat/beater/aws_kube_fetcher.go
> +func (f AwsKubeFetcher) GetNodeDescription() ([]interface{}, error) {
Changed

2021-12-16 11:47 UTC, ofiriro3 commented on kubebeat/beater/aws_kube_fetcher.go
> +	return nodesInfo, err
right - I started with filtering the node information and later on, I removed it - I fixed it now

2021-12-16 11:49 UTC, ofiriro3 commented on kubebeat/beater/ecr_provider.go
> +/// When repoNames is nil, it will describe all the existing repositories
What do you mean? 
it's part of the API

2021-12-16 11:50 UTC, ofiriro3 commented on kubebeat/beater/ecr_provider.go
> +		logp.Err("Failed to fetch repository:%s from ecr, error - %+v", repoNames, err)
It will get all the ECR repositories

2021-12-16 12:24 UTC, eyalkraft commented on kubebeat/beater/ecr_provider.go
> +		logp.Err("Failed to fetch repository:%s from ecr, error - %+v", repoNames, err)
I'm talking about the logging. you format here a `nil` value with `%s` which is probably unsafe

2021-12-16 12:25 UTC, eyalkraft commented on kubebeat/beater/ecr_provider.go
> +/// When repoNames is nil, it will describe all the existing repositories
It's part of the AWS API. It doesn't mean it is supposed to be a part if your function's API. I think in this case it's better to encapsulate it, especially since we never use this argument in the rest of the code.

2021-12-16 12:32 UTC, eyalkraft commented on kubebeat/beater/aws_kube_fetcher.go
> +	ctx2, cancel2 := context.WithTimeout(context.TODO(), 30*time.Second)
I think they can be private like you suggested but I don't like things like magic timeouts hidden throughout the code, Especially when they differ from one another. For me passing a context from outside and having all the timeouts in front of my eyes in the `Fetch` function is more elegant. another approach could be using constants but it's less elegant IMO.

2021-12-16 12:51 UTC, eyalkraft commented on kubebeat/beater/Iam_provider.go
> +	svc := iam.New(cfg)
I recommend going through some of AWS docs. Seems like the optimal way would be to create a session and then using it to create the service clients.

 > The SDK removes the complexity of coding directly against a web service interface. It hides a lot of the lower-level plumbing, such as authentication, request retries, and error handling.

https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html
https://docs.aws.amazon.com/sdk-for-go/api/
https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/making-requests.html

2021-12-19 13:13 UTC, Ofir-Lapid commented on kubebeat/beater/ecr_provider.go
> +		logp.Err("Failed to fetch repository:%s from ecr, error - %+v", repoNames, err)
Checked it, it will just print an empty array

2021-12-19 13:14 UTC, Ofir-Lapid commented on kubebeat/beater/ecr_provider.go
> +/// When repoNames is nil, it will describe all the existing repositories
The idea was to create a provider, that will later serves other calls, I have an idea to make it pretty - I'll do it

2021-12-19 15:01 UTC, Ofir-Lapid commented on kubebeat/beater/Iam_provider.go
> +	svc := iam.New(cfg)
Hi, 

You looked at the wrong documentation, we are working with version 2 ->https://github.com/aws/aws-sdk-go-v2

Anyhow, I thought a lot about creating a stateless provider, and I decided to make it stateful.
 I am a bit afraid of connection exhaustion to AWS, I would assume that AWS under the hood knows how to recycle old client with a client pool or such, but just in case they didn't - I made it stateful.

I tried to find a "best practices" for GO SDK and I couldn't :/

2021-12-19 15:16 UTC, Ofir-Lapid commented on go.mod
> +require go.uber.org/goleak v1.0.0
I am wondering why it is here, it should be related to @yashtewari code

2021-12-19 15:18 UTC, Ofir-Lapid commented on kubebeat/Dockerfile
> +RUN apt-get update
In order for the beats to recognize the Elastic could, it needs to have this package

2021-12-21 08:46 UTC, amirbenun commented on kubebeat/beater/Iam_provider.go
> +package beater
filename lowercase

2021-12-21 11:47 UTC, eyalkraft approved these changes
Could be further improved with some refactor ideas @Ofir-Lapid explained to me on a call.
Since it works and we are about to have multiple refactors in the fetchers are also in the kube-api fetcher, LGTM for now.

2021-12-22 09:46 UTC, amirbenun approved these changes

2021-12-22 09:46 UTC, amirbenun commented on kubebeat/pod.yml
> +      imagePullPolicy: Always
I wonder about that, where should it pull the image from?
Usually, you just run `minikube image load kubebeat` and the image will be available to you from within the cluster.
So why is it necessary?

2021-12-22 10:03 UTC, ofiriro3 commented on kubebeat/pod.yml
> +      imagePullPolicy: Always
When working with a registry provider, you want the image to be pulled every time you run the pod.yml.

If not changed, if you have an old image it will use it instead of the new one.

2021-12-22 10:09 UTC, amirbenun commented on kubebeat/pod.yml
> +      imagePullPolicy: Always
👍

2021-12-22 10:10 UTC, merged