working integration v1(ILM issue exists in bit)
build-security/beats pull request #34
Opened 2021-12-20 11:17 UTC by DaveSys911

## What does this PR do?

## Why is it important?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2021-12-20 13:29 UTC, eyalkraft commented on kubebeat/beater/evaluation_result_parser.go
> +		event.Meta = common.MapStr{libevents.FieldMetaRawIndex: index}
```suggestion
		event.Meta = common.MapStr{libevents.FieldMetaIndex: index}
```
Try that as it's supposed to take precedence over `FieldMetaRawIndex`

2021-12-21 09:21 UTC, eyalkraft commented on kubebeat/beater/evaluation_result_parser.go
> +		event.Meta = common.MapStr{libevents.FieldMetaRawIndex: index}
OK for now, to be fixed in a later PR.

2021-12-21 12:33 UTC, eyalkraft requested changes

2021-12-21 12:33 UTC, eyalkraft commented on kubebeat/config/config.go
> +type DatastreamConfig struct {
is this type used?

2021-12-21 12:33 UTC, eyalkraft commented on kubebeat/beater/kubebeat.go
> +				bt.resourceIteration(config.Datastream(ns), resource, runId, timestamp)
There is no reason for doing it over and over again.
what about moving this calculation to the `New` function, and save the index as a field in the `kubebeat` struct?

2021-12-21 12:33 UTC, eyalkraft commented on kubebeat/beater/kubebeat.go
> +				ns := ""
This is dirty as it has nothing to do with the actual namespace the agent belongs to. try figuring out how to get the real namespace and use it.

2021-12-21 12:33 UTC, eyalkraft commented on kubebeat/beater/kubebeat.go
> +func (bt *kubebeat) resourceIteration(index, resource interface{}, runId uuid.UUID, timestamp time.Time) {
do this Todo - see my previous suggestion on having a `bt.index` field calculated once.

2021-12-21 12:33 UTC, eyalkraft commented on kubebeat/beater/kubebeat.go
> +	events, err := bt.resultParser.ParseResult(index, result, runId, timestamp)
Parsing the result really has nothing to do with the index logically.
Since this is temporal until we figure out how define the index in the proper way, I think a better approach would be to iterate through the events here and add them the relevant field.
Leave a comment explaining why this is what you did and what should be done to later fix it.

2021-12-21 12:33 UTC, eyalkraft commented on kubebeat/beater/evaluation_result_parser.go
> +func (parser *evaluationResultParser) ParseResult(index, result interface{}, uuid uuid.UUID, timestamp time.Time) ([]beat.Event, error) {
The index isn't a concern of the result parser (IMO this file shouldn't have changes).
Try keeping the changes in the proper place logically (index concerns probably belong where the beat is configured and started).

2021-12-21 12:33 UTC, eyalkraft commented on kubebeat/beater/evaluation_result_parser.go
> +		event.Meta = common.MapStr{libevents.FieldMetaIndex: index}
see my previous suggestion to move this outside of this function.

2021-12-21 12:33 UTC, eyalkraft commented on kubebeat/config/config.go
> +// function to generate the datastream value
Golang has some docs standards. most IDEs could be configured to generate the proper format for you to later edit.

2021-12-21 12:33 UTC, eyalkraft commented on kubebeat/beater/kubebeat.go
> +	events, err := bt.resultParser.ParseResult(index, result, runId, timestamp)
Better yet - From what I see in other beats, I think the proper way of doing this is adding a processor to the publisher. see `add_data_stream.go` and `add_formatted_index.go` and their usages.

2021-12-21 12:36 UTC, eyalkraft commented
This is the most interesting part IMO https://github.com/build-security/beats/pull/34#discussion_r773098088

2021-12-21 13:04 UTC, DaveSys911 commented on kubebeat/JUSTFILE
> +  elastic-package stack up --version=8.1.0-SNAPSHOT
It's an option that some will need. i want to avoid adding that to the beats readme and prefer to have a just command.
Remember it's a temp solution and will be transferred to make/mage.

2021-12-21 13:08 UTC, DaveSys911 commented on kubebeat/config/config.go
> +type DatastreamConfig struct {
will be implemented in https://github.com/elastic/security-team/issues/2383 and passed from fleet. i can remove it for now

2021-12-21 13:10 UTC, DaveSys911 commented on kubebeat/beater/kubebeat.go
> +				bt.resourceIteration(config.Datastream(ns), resource, runId, timestamp)
This depends on the fetcher & data design.
Right now I'm not sure if we will use the same datastream/index for all events.
Or if we split the fetchers to streams or leave it as a single input.

I'd prefer it to be done in a separate task after we do design for https://github.com/elastic/security-team/issues/2383
and decide on if we will use streams to split our inputs.

2021-12-21 13:21 UTC, DaveSys911 commented on kubebeat/beater/kubebeat.go
> +				ns := ""
It's the elk "Namespace" not the k8s. The streams are suffixed with the ns to avoid collision on multi tenant kibana.
https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/namespaces.html

it also to logically segregated data(somewhat like k8s namespaces for pods,but for ES indexes)

2021-12-21 13:22 UTC, DaveSys911 commented on kubebeat/beater/kubebeat.go
> +	events, err := bt.resultParser.ParseResult(index, result, runId, timestamp)
Added todo to address this as a subsequent task, since this implementation is depended on other efforts.

2021-12-21 13:22 UTC, DaveSys911 commented on kubebeat/beater/kubebeat.go
> +func (bt *kubebeat) resourceIteration(index, resource interface{}, runId uuid.UUID, timestamp time.Time) {
Added todo to address this as a subsequent task, since this implementation is depended on other efforts.

2021-12-21 13:34 UTC, DaveSys911 commented on kubebeat/beater/kubebeat.go
> +	events, err := bt.resultParser.ParseResult(index, result, runId, timestamp)
I will add it to the polishing gh issue together with the rest, can tackle it as part of #2383 (add configuration options).

The infra for index provisions should be designed after we establish the "kubebeat" reconfig, namespace var consumption and decide on the fetchers/streams.

It should also potentially accommodate ilm, templates and ingest pipelines or at least have place holders and designed for that in mind.

2021-12-21 14:29 UTC, eyalkraft commented on kubebeat/beater/kubebeat.go
> +				ns := ""
I know, I was talking about the elk namespace.

2021-12-22 10:45 UTC, eyalkraft approved these changes
Approved without the fixes to allow David to set up a shared demo environment.
These comment will be handled in the next task https://github.com/elastic/security-team/issues/2383

2021-12-22 11:19 UTC, amirbenun commented on kubebeat/beater/kubebeat.go
> +	events, err := bt.resultParser.ParseResult(index, result, runId, timestamp)
I agree with @eyalkraft about the comment. I think we should discuss it should be done on the current pr or not. @DaveSys911 how complex will it be to implement one of the solutions that Eyal suggested?

2021-12-27 21:22 UTC, merged