Add leader election logic
build-security/beats pull request #42
Opened 2022-01-05 09:23 UTC by yashtewari

The simplest way to use existing Kubernetes leader election capabilities implemented by Elastic Agent is to publish the status to the environment using environment variable.

This is then consumed by our beat.

2022-01-05 10:37 UTC, amirbenun reviewed
Looks good!

2022-01-05 10:37 UTC, amirbenun commented on kubebeat/beater/kube.go
> +	})
Just to make sure I got you right, you are trying to avoid initializing watchers on an agent that is not the leader?
Do we understand what does it mean to initialize a watcher in terms of the network?

2022-01-05 10:37 UTC, amirbenun commented on x-pack/elastic-agent/pkg/composable/providers/kubernetesleaderelection/kubernetes_leaderelection.go
> +
Is it part of the k8s API  or just a workaround for us?

2022-01-05 11:24 UTC, yashtewari commented on kubebeat/beater/kube.go
> +	})
Calls to the Kube API are made and cache is built up only when `Start` is called on a Watcher, and not when it is created. `initWatchers` does both steps of creating and starting the watchers. Of these, only the second is relevant in terms of performance.

We could move the creation part out of this `sync.Once.Do` call, indeed this is how it was in my earlier commit which we decided to remove and make a separate part out of. But I don't think it makes a difference.

2022-01-05 11:29 UTC, yashtewari commented on x-pack/elastic-agent/pkg/composable/providers/kubernetesleaderelection/kubernetes_leaderelection.go
> +
This is Elastic Agent code, it is using Kube functionality to try to elect itself as leader. This already works with the whole Elastic Agent Daemonset setup.

The envar is just a way to communicate the information to our beat. I considered some other ways to do this, they would involve a lot of changes in the existing beats codebase, so decided to go with this method for now.

2022-01-19 12:59 UTC, amirbenun commented on x-pack/elastic-agent/pkg/composable/providers/kubernetesleaderelection/kubernetes_leaderelection.go
> +
It feels to me like it's going to make it even harder to merge to beats.
What do you think?

2022-01-19 13:55 UTC, yashtewari commented on x-pack/elastic-agent/pkg/composable/providers/kubernetesleaderelection/kubernetes_leaderelection.go
> +
This implementation has been replaced with a different one.

2022-01-19 14:36 UTC, amirbenun requested changes

2022-01-19 14:36 UTC, amirbenun commented on kubebeat/beater/profile.cov
> +mode: set
remove

2022-01-19 14:36 UTC, amirbenun commented on x-pack/elastic-agent/pkg/composable/providers/kubernetesleaderelection/kubernetes_leaderelection.go
> +
remove the file

2022-01-19 14:36 UTC, amirbenun commented on x-pack/elastic-agent/pkg/composable/providers/kubernetesleaderelection/config.go
> +const (
remove

2022-01-20 07:22 UTC, yashtewari commented on kubebeat/beater/kube_lease.go
> +	leases, err := l.client.CoordinationV1().Leases(kubeSystemNamespace).List(l.ctx, v1.ListOptions{})
Yes that's where it is

2022-01-20 08:58 UTC, amirbenun approved these changes

2022-01-20 09:07 UTC, amirbenun approved these changes

2022-01-20 09:43 UTC, merged