Data, Fetcher, Fetcher implementations
build-security/beats pull request #8
Opened 2021-11-11 08:34 UTC by yashtewari

## What does this PR do?

## Why is it important?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- 

## Use cases

## Screenshots

## Logs

2021-11-11 12:55 UTC, ofiriro3 approved these changes

2021-11-11 13:09 UTC, amitkanfer commented on kubebeat/proc/stat.go
> +func ReadStat(root string, pid string) (stat ProcStat, err error) {
damn... isn't there something that does this already in go?
Seems too low level... but i might be wrong

2021-11-11 14:09 UTC, ofiriro3 commented
I like the abstraction that you used.

I am just wondering if we should add the fetcher interface (and maybe some of the implementations) to the Kubebeat, or add it to a common libBeat. For now, It is sufficient to leave it as it is, but in the future, we would like to at least decouple it from the Kubebeat package and move it to a different package.

Anyhow, GJ!

BTW, I have already made a fileFetcher for the file system based on your code.

2021-11-11 14:55 UTC, eyalkraft requested changes
Great work, I haven't yet deep dived to every single file here but so far I see a few problems:
1. The current interface and Implementation results in us having the whole cluser data in-memory twice. Once inside `KubeFetcher.watcher.Store()` and a second time in `data.state["kube_api"]`.
2. If we have all the state in-memory, why copy it repeatedly instead of having it in OPA the whole time?
3. In this implementation we will keep al state in memory. see @kfirpeled s [comment](https://github.com/elastic/security-team/issues/1970#:~:text=I%20think%20we%20should%20assume%20the%20number%20of%20resources%20can%20be%20a%20huge%20number) on my issue stating why this might be a problematic approach (huge amount of data).

 Nit: it's Elasticsearch N.V. (not B.V.)

2021-11-11 14:55 UTC, eyalkraft commented on kubebeat/beater/kubebeat.go
> +	err := bt.data.Run()
data is never stopped

2021-11-11 15:21 UTC, kfirpeled commented on kubebeat/proc/list.go
> +			err = nil
do we have a logger in the beat? i would suggest logging whenever you get an error for some reason that is being silenced. It is helpful for debugging

2021-11-11 15:21 UTC, kfirpeled commented on kubebeat/beater/kube.go
> +		Namespace:   "kube-system",
should the namespace be a parameter? so we could better re-use it in the future?

2021-11-11 15:21 UTC, kfirpeled commented on kubebeat/beater/kubebeat.go
> +			bt.client.PublishAll(events)
Hey @yashtewari lets discuss on the output to the findings index
We started a discussion for the purpose of our first sprint [here](https://github.com/elastic/security-team/issues/2190)

I am aware it differ from the proposal started https://github.com/elastic/security-team/issues/2017. For the sake of our first sprint we want to keep it simple until we will have a final proposition

2021-11-11 15:43 UTC, amirbenun commented on kubebeat/beater/kubebeat.go
> +			bt.client.PublishAll(events)
That's just a temporary implementation, later on the implementation will comply with whatever we decide.

2021-11-11 15:55 UTC, amirbenun approved these changes

2021-11-11 16:02 UTC, ofiriro3 approved these changes

2021-11-11 16:04 UTC, Ofir-Lapid approved these changes

2021-11-15 10:02 UTC, merged

2021-11-15 10:03 UTC, yashtewari commented
Merged as per discussion today. Thank you for all your comments, will continue to address them. @Ofir-Lapid you are good to go!

2021-11-16 11:59 UTC, yashtewari commented on kubebeat/proc/stat.go
> +func ReadStat(root string, pid string) (stat ProcStat, err error) {
Among open source packages, [Prometheus' procfs](https://pkg.go.dev/github.com/prometheus/procfs) seems to be the only one that's mature and current. It comes with a warning though: it can break in backwards incompatible ways at any time.

That's probably why Aleks from the osquerybeat [made this implementation](https://github.com/elastic/beats/tree/master/x-pack/osquerybeat/ext/osquery-extension/internal/proc) that I've copied for convenience. It's not usable directly as it's an [internal package](https://golang.org/doc/go1.4#internalpackages).

I sense that there's another implementation in metricbeat, and I'm looking for that one. In any case, this is just a copy as mentioned in the first commit on the PR, and is not meant to be reviewed here.

2021-11-16 12:00 UTC, yashtewari commented on kubebeat/proc/list.go
> +			err = nil
The changes under the first commit are not meant to be reviewed in this PR, see: https://github.com/build-security/beats/pull/8#discussion_r750200090

2021-11-16 12:01 UTC, yashtewari commented on kubebeat/beater/kube.go
> +		Namespace:   "kube-system",
Definitely! This is a very rough rearrange-and-go of older code. It's far from perfect, and that's one of the things I'm adding in my Kube API task for this sprint.

2021-11-16 12:02 UTC, yashtewari commented on kubebeat/beater/kubebeat.go
> +	err := bt.data.Run()
Woops, will fix.